select * from customer limit 20


--Q1. What is the total revenue generated by male vs. female customers?
select gender,  SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric), 2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
AVG(purchase_amount
)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers?
select  subscription_status,
COUNT(customer_id) as ttotal_custoomers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;
--Q6. Which 5 products have the highest percentage of purchase with discounts applied?
SELECT item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment.
SELECT 
    CASE 
        WHEN Previous_Purchases = 1 THEN 'New'
        WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS Customer_Segment,
    COUNT(*) AS Segment_Count
FROM customer
GROUP BY Customer_Segment
ORDER BY Segment_Count DESC;


--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        Category,
        Item_Purchased,
        COUNT(customer_id) AS total_orders
    FROM customer
    GROUP BY Category, Item_Purchased
),

ranked_items AS (
    SELECT 
        ROW_NUMBER() OVER (PARTITION BY Category ORDER BY total_orders DESC) AS item_rank,
        Category, 
        Item_Purchased, 
        total_orders
    FROM item_counts
)

SELECT 
    item_rank,
    Category, 
    Item_Purchased, 
    total_orders
FROM ranked_items
WHERE item_rank <= 3
ORDER BY Category, item_rank;


--Q9. Are customers who are repeat buyers (with more than 5 previous purchases)also likely to subscribe?

SELECT 
    CASE 
        WHEN Previous_Purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS Buyer_Type,
    Subscription_Status,
    COUNT(*) AS customer_count
FROM customer
GROUP BY Buyer_Type, Subscription_Status
ORDER BY Buyer_Type, Subscription_Status;

--Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(Purchase_Amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

